# https://stackoverflow.com/questions/53738437/php-application-cant-connect-to-mariadb-using-docker-compose
version: "3.8"
services:
  web:
    links: 
      - db
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8090:8090"
    restart: always  
    image: cms-simulator:1.0.0
    container_name: cms-simulator
    expose: 
      - 8090
    environment:       
      - DATABASE_URL=jdbc:mariadb://db:3306/cms
      - DATABASE_USERNAME=cmsuser
      - DATABASE_PASSWORD=cmspass
      - GRPC_SERVER_HOST=cms-rpc
      - GRPC_SERVER_PORT=8000
    networks: 
      - sp-cms_cms-network

  db:
    image: mariadb
    container_name: mariadb
    command: --init-file /data/init.sql
    volumes:
      - ./init.sql:/data/init.sql
      # - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:      
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cms
      MYSQL_USER: cmsuser
      MYSQL_PASSWORD: cmspass
    networks: 
      - sp-cms_cms-network

networks:
  sp-cms_cms-network:
    external: true