version: "3.8"

services:

  web:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8090:8090"
    restart: always  
    image: cms-simulator:1.0.0
    container_name: cms-simulator
    networks:
      local1:
        ipv4_address: 10.10.10.2
    depends_on: 
      - "db"

  db:
    image: mariadb
    container_name: mariadb-1
    command: --init-file /data/init.sql
    volumes:
      - ./init.sql:/data/init.sql
    ports:
      - "3307:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      local1:
        ipv4_address: 10.10.10.10

networks:
  local1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/28
