# https://stackoverflow.com/questions/53738437/php-application-cant-connect-to-mariadb-using-docker-compose
version: "3.8"
services:
  web:
    links:
      - db
    build:
      dockerfile: dockerfile
      context: .
    ports:
      - "8090:8090"
    restart: always
    image: superpay-cms-simulator
    container_name: superpay-cms-simulator
    expose:
      - 8090
    environment:
      - DATABASE_URL=jdbc:mariadb://db:3306/cms
      - DATABASE_USERNAME=cmsuser
      - DATABASE_PASSWORD=cmspass
      # - GRPC_SERVER_HOST=superpay-cms-server
      # - GRPC_SERVER_PORT=8000
      - GRPC_SERVER_HOST=172.25.25.74
      - GRPC_SERVER_PORT=31076
    networks:
      - superpay_network

  db:
    image: mariadb
    container_name: superpay-cms-mariadb
    command: --init-file /data/init.sql
    volumes:
      - ./init.sql:/data/init.sql
      # - ./mysql:/var/lib/mysql
    ports:
      - "43306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cms
      MYSQL_USER: cmsuser
      MYSQL_PASSWORD: cmspass
    networks:
      - superpay_network

networks:
  superpay_network:
    external: true