CREATE DATABASE cms_db;
CREATE USER cms1@'%' IDENTIFIED BY 'FA7sD=cSbL}h?,G^';
GRANT ALL PRIVILEGES ON cms_db.* TO cms1@'%';
CREATE USER cms1@localhost IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON cms_db.* TO cms1@localhost;
